//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulatKhasanov
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildObject
    {
        public override string ToString()
        {
            return this.Name;
        }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ContactPerson { get; set; }
        public string CustomerNumber { get; set; }
    
        public virtual Plan Plan { get; set; }
    }
}
