//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulatKhasanov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public override string ToString()
        {
            return this.WorkName;
        }
        public int Id { get; set; }
        public string WorkName { get; set; }
        public int Price { get; set; }
        public int Scale { get; set; }
        public bool IsDone { get; set; }
        public Nullable<int> PlanContractNumber { get; set; }
        public int EmployeeId { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
